#!/usr/bin/env ruby

require 'rbbt/util/semaphore'
require 'rbbt/workflow'

Workflow.require_workflow "Study"
require 'rbbt/entity/study'
require 'rbbt/entity/study/genotypes'
require 'rbbt/entity/study/cnv'
#require 'rbbt/entity/study/expression'
#require 'rbbt/entity/study/cnv/knowledge_base'

Workflow.require_workflow "ICGC"
require 'rbbt/entity/gene'
require 'rbbt/entity/genomic_mutation'


datasets = ICGC.job(:datasets).run.keys

num = ARGV.shift || "1"

Study.study_dir = ICGC.root

Log.debug("Producing")
datasets.each do |dataset|
    study = Study.setup(dataset)
    Log.debug("Producing #{ dataset }")
    study.samples
end

Log.debug("Bootstrapping over #{num.to_i} processes")
RbbtSemaphore.fork_each_on_semaphore(datasets, num.to_i) do |dataset|
    study = Study.setup(dataset)
    Log.debug("Bootstrapping #{ dataset } - #{study.samples.length}")
    study = Study.setup(dataset)
    study.knowledge_base.get_database(:sample_genes) if study.has_genotypes?
end
