#rule '.' do |t|
#  dataset = File.basename(File.expand_path('.'))
#  ICGC.job(:prepare_study, dataset, :dataset => dataset, :output => '.').recursive_clean.run
#end


ICGC.job(:datasets).run.each do |dataset, values|
  rule /^(#{Regexp.quote dataset})\/metadata\.yaml$/ do |t|
    dataset = t.name.split("/").first
    ICGC.job(:prepare_study, dataset, :dataset => dataset, :output => dataset).recursive_clean.run
  end

  #rule /^(#{Regexp.quote dataset})\/.*$/ => lambda{|f| File.join(f.split("/").first, "metadata.yaml")} do |t|
  #end

  rule /^(#{Regexp.quote dataset})$/ => lambda{|f| File.join(f.split("/").first, "metadata.yaml")} do |t|
  end
end
